import type { Evidence, ReportData } from "./build.js";

/** Markdown rendering of the engagement report (the CLI-facing projection). */
function evidenceLines(evidence: Evidence[]): string[] {
  const lines: string[] = [];
  for (const e of evidence.slice(0, 3)) {
    lines.push(`  - ${e.statement}`);
    if (e.quote) lines.push(`    > ${e.quote.replace(/\n/g, " ")}`);
    lines.push(`    source: ${e.sourceUri}${e.speaker ? ` — ${e.speaker}` : ""}`);
  }
  return lines;
}

export function reportMarkdown(report: ReportData): string {
  const md: string[] = [
    `# Engagement report — ${report.engagement}`,
    "",
    `Generated ${report.generatedAt.slice(0, 10)} from ${report.coverage.episodes} sessions, ` +
      `${report.coverage.activeFacts} verified facts` +
      (report.coverage.speakers.length
        ? `, interviews with ${report.coverage.speakers.join(", ")}`
        : "") +
      ". Every claim below links back to its source.",
    "",
    "## 1. What we can take off your team's plate",
    "",
  ];

  if (report.painPoints.length === 0 && report.tasks.proposed.length === 0) {
    md.push("_No opportunities recorded yet — ingest interview material first._");
  }
  for (const p of report.painPoints) {
    md.push(
      `- **${p.name}**${p.reporters.length ? ` — reported by ${p.reporters.join(", ")}` : ""}`,
      ...evidenceLines(p.evidence),
      "",
    );
  }

  md.push("## 2. Where the hours go today", "");
  const quantified = report.painPoints.filter((p) => p.quantified);
  const unquantified = report.painPoints.filter((p) => !p.quantified);
  if (report.painPoints.length === 0) md.push("_No pain points recorded yet._");
  if (quantified.length > 0) {
    for (const p of quantified) md.push(`- **${p.name}**`, ...evidenceLines(p.evidence), "");
  }
  if (unquantified.length > 0) {
    md.push(
      `${unquantified.length} opportunity(ies) still need numbers — see the quantification questions in section 4.`,
      "",
    );
  }

  md.push("## 3. What gets replaced", "");
  if (report.automations.length === 0) {
    md.push("_No automation coverage recorded yet._");
  }
  for (const a of report.automations) {
    md.push(`- **${a.step}** ← automated by \`${a.asset}\``, ...evidenceLines(a.evidence), "");
  }
  if (report.tasks.delivered.length > 0) {
    md.push("", "Delivered and accepted:");
    for (const t of report.tasks.delivered) {
      md.push(`- ${t.title}${t.outcome ? ` — outcome: ${t.outcome}` : ""}`);
    }
  }

  md.push("", "## 4. Value and next steps", "");
  const statusLine = Object.entries(report.tasks.byStatus)
    .map(([s, n]) => `${n} ${s}`)
    .join(" · ");
  md.push(
    `Task pipeline: ${statusLine || "empty"}.`,
    "",
    `Constraints we will respect (${report.constraints.length}):`,
    "",
  );
  for (const c of report.constraints) md.push(`- ${c.statement} (${c.sourceUri})`);

  if (report.activity.length > 0) {
    md.push("", "Recent activity:", "");
    for (const a of report.activity.slice(0, 8)) {
      const what =
        a.kind === "status"
          ? `${a.fromStatus} -> ${a.toStatus}`
          : a.kind === "created"
            ? "created"
            : "note";
      md.push(
        `- ${a.at.slice(0, 16).replace("T", " ")} · ${a.taskTitle} · ${what}` +
          `${a.actor ? ` (${a.actor})` : ""}${a.note ? `: ${a.note}` : ""}`,
      );
    }
  }

  if (report.quantifyQuestions.length > 0) {
    md.push(
      "",
      "To turn this into a hard number, we need answers to:",
      "",
      ...report.quantifyQuestions.map((q) => `- ${q}`),
    );
  } else if (report.painPoints.length > 0) {
    md.push("", "All recorded opportunities carry quantitative evidence.");
  }

  md.push("", "---", "_Generated by openfde from the engagement memory. Numbers are only claimed where sources contain them._");
  return md.join("\n");
}
